# Generated by Django 5.0.2 on 2024-02-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_remove_usermessage_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
