# Generated by Django 5.0.2 on 2024-02-12 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('ship_date', models.DateTimeField(blank=True, null=True)),
                ('payment', models.BooleanField(default=False)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('status', models.CharField(choices=[('Pending', 'รอดำเนินการ'), ('Processing', 'ยืนยันคำสั่งซื้อ'), ('Measuring', 'นัดวัดขนาด'), ('Material Selection', 'เลือกวัสดุ'), ('In Progress', 'ดำเนินการ'), ('Ready for Shipping', 'เสร็จสิ้น'), ('Installation', 'ติดตั้ง'), ('Completed', 'เสร็จสิ้น'), ('Cancelled', 'ยกเลิก')], default='Pending', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
