# Generated by Django 5.0.2 on 2024-02-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_order_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
