# Generated by Django 5.0.2 on 2024-02-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_order_delivery_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
