# Generated by Django 5.0.2 on 2024-02-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_order_first_name_alter_order_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('รอดำเนินการ', 'รอดำเนินการ'), ('ยืนยันคำสั่งซื้อ', 'ยืนยันคำสั่งซื้อ'), ('นัดวัดขนาด', 'นัดวัดขนาด'), ('เลือกวัสดุ', 'เลือกวัสดุ'), ('ดำเนินการ', 'ดำเนินการ'), ('พร้อมติดตั้ง', 'พร้อมติดตั้ง'), ('ติดตั้ง', 'ติดตั้ง'), ('เสร็จสิ้น', 'เสร็จสิ้น'), ('ยกเลิก', 'ยกเลิก')], default='รอดำเนินการ', max_length=20),
        ),
    ]
