# Generated by Django 5.0.2 on 2024-02-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_usermessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='message',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='line_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
