# Generated by Django 5.0.2 on 2024-02-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_remove_usermessage_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
