# Generated by Django 5.0.2 on 2024-03-13 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_delete_usermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h', models.FloatField(default=0)),
                ('w', models.FloatField(default=0)),
                ('d', models.FloatField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.order')),
            ],
        ),
    ]
