# Generated by Django 5.0.3 on 2024-04-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('รอดำเนินการ', 'รอดำเนินการ'), ('ยืนยันคำสั่งซื้อ', 'ยืนยันคำสั่งซื้อ'), ('ดำเนินการ', 'ดำเนินการ'), ('ติดตั้ง', 'ติดตั้ง'), ('เสร็จสิ้น', 'เสร็จสิ้น'), ('ยกเลิก', 'ยกเลิก')], default='รอดำเนินการ', max_length=20),
        ),
    ]
