# Generated by Django 5.0.3 on 2024-05-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_order_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deposit_proof',
            field=models.ImageField(blank=True, null=True, upload_to='deposit_proofs/'),
        ),
    ]
