# Generated by Django 5.0.3 on 2024-05-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_cancelorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelorder',
            name='order',
        ),
    ]
