# Generated by Django 5.0.3 on 2024-05-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_cancelorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuresize',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='MeasureSize/'),
        ),
        migrations.AddField(
            model_name='measuresize',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='MeasureSize/'),
        ),
        migrations.AddField(
            model_name='measuresize',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='MeasureSize/'),
        ),
        migrations.AddField(
            model_name='measuresize',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='MeasureSize/'),
        ),
        migrations.AddField(
            model_name='measuresize',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='MeasureSize/'),
        ),
        migrations.AddField(
            model_name='measuresize',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
