# Generated by Django 5.0.3 on 2024-05-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_measuresize_image1_measuresize_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuresize',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='MeasureSize/'),
        ),
    ]
