# Generated by Django 5.0.3 on 2024-05-14 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_measuresize_image6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuresize',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MeasureSize', to='members.order'),
        ),
    ]
