# Generated by Django 5.0.3 on 2024-05-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_alter_measuresize_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_pay',
            field=models.IntegerField(default=0),
        ),
    ]
