# Generated by Django 5.0.3 on 2024-05-20 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_remove_product_material'),
        ('members', '0025_order_total_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureSizeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_measure_sizes', to='manager.material')),
                ('measure_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measure_size_materials', to='members.measuresize')),
            ],
        ),
    ]
