# Generated by Django 5.0.3 on 2024-05-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_measuresizematerial_unique_measure_size_material'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='measuresizematerial',
            name='unique_measure_size_material',
        ),
    ]
