# Generated by Django 5.0.3 on 2024-05-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_remove_measuresizematerial_unique_measure_size_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='appt_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
