# Generated by Django 5.0.3 on 2024-05-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0034_alter_order_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='install_proofs/'),
        ),
        migrations.AddField(
            model_name='order',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='install_proofs/'),
        ),
        migrations.AddField(
            model_name='order',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='install_proofs/'),
        ),
        migrations.AddField(
            model_name='order',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='install_proofs/'),
        ),
    ]
