# Generated by Django 5.0.3 on 2024-06-19 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0036_alter_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CancellationReason',
        ),
    ]
