# Generated by Django 5.0.2 on 2024-03-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_product_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h', models.FloatField(default=0)),
                ('w', models.FloatField(default=0)),
                ('d', models.FloatField(default=0)),
            ],
        ),
    ]
