# Generated by Django 5.0.2 on 2024-03-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_measuresize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeasureSize',
        ),
    ]
