# Generated by Django 5.0.3 on 2024-05-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_product_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.IntegerField(default=0),
        ),
    ]
