# Generated by Django 5.0.3 on 2024-05-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_product_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='product_deposit',
        ),
    ]
