# Generated by Django 5.0.3 on 2024-05-18 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_rename_product_product_product_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
    ]
