# Generated by Django 5.0.3 on 2024-05-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='production_time',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_deposit',
            field=models.IntegerField(default=50),
        ),
    ]
