# Generated by Django 5.0.3 on 2024-06-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_workingday'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingday',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
