# Generated by Django 5.0.3 on 2024-06-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_workingday_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingday',
            name='is_open',
        ),
    ]
